/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得商品列表 */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康檢查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            /**
             * Format: int64
             * @description 商品 ID
             * @example 1
             */
            id?: number;
            /**
             * @description 商品名稱
             * @example Coffee
             */
            name?: string;
            /**
             * Format: double
             * @description 價格
             * @example 4.5
             */
            price?: number;
            /**
             * Format: int32
             * @description 庫存數量
             * @example 100
             */
            stock?: number;
            /**
             * @description 商品分類
             * @example drinks
             */
            category?: string;
            /**
             * @description 商品貨號
             * @example SKU-001
             */
            sku?: string;
            /**
             * @description 供應商
             * @example ACME
             */
            supplier?: string;
        };
        Health: {
            /**
             * @description 服務狀態
             * @example ok
             */
            status?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Product"][];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Health"];
                };
            };
        };
    };
}
